export default {
  name: 'ResDes Basic',
  slug: 'resdes-basic',
  version: '1.0.0',
  author: 'Resonance Designs',
  description: 'Starter theme for ResDesCMS demonstrating custom CSS + settings.',
  style: 'style.css',
  settingsSchema: [
    { key: 'primaryColor', label: 'Primary Color', type: 'color', default: '#e06e26' },
    { key: 'accentColor', label: 'Accent Color', type: 'color', default: '#319ea4' },
    { key: 'textColor', label: 'Body Text Color', type: 'color', default: '#1f2933' },
    { key: 'backgroundColor', label: 'Page Background', type: 'color', default: '#f9fafb' },
    { key: 'maxWidth', label: 'Content Max Width (px)', type: 'number', default: 1200 },
    { key: 'containerPaddingTop', label: 'Container Padding Top (px)', type: 'number', default: 0 },
    { key: 'containerPaddingRight', label: 'Container Padding Right (px)', type: 'number', default: 0 },
    { key: 'containerPaddingBottom', label: 'Container Padding Bottom (px)', type: 'number', default: 0 },
    { key: 'containerPaddingLeft', label: 'Container Padding Left (px)', type: 'number', default: 0 },
    { key: 'containerMarginTop', label: 'Container Margin Top (px)', type: 'number', default: 0 },
    { key: 'containerMarginRight', label: 'Container Margin Right (px)', type: 'number', default: 0 },
    { key: 'containerMarginBottom', label: 'Container Margin Bottom (px)', type: 'number', default: 0 },
    { key: 'containerMarginLeft', label: 'Container Margin Left (px)', type: 'number', default: 0 },
    { key: 'headerPaddingTop', label: 'Header Padding Top (px)', type: 'number', default: 16 },
    { key: 'headerPaddingRight', label: 'Header Padding Right (px)', type: 'number', default: 16 },
    { key: 'headerPaddingBottom', label: 'Header Padding Bottom (px)', type: 'number', default: 16 },
    { key: 'headerPaddingLeft', label: 'Header Padding Left (px)', type: 'number', default: 16 },
    { key: 'headerMarginTop', label: 'Header Margin Top (px)', type: 'number', default: 0 },
    { key: 'headerMarginRight', label: 'Header Margin Right (px)', type: 'number', default: 0 },
    { key: 'headerMarginBottom', label: 'Header Margin Bottom (px)', type: 'number', default: 0 },
    { key: 'headerMarginLeft', label: 'Header Margin Left (px)', type: 'number', default: 0 },
    { key: 'bodyPaddingTop', label: 'Body Padding Top (px)', type: 'number', default: 32 },
    { key: 'bodyPaddingRight', label: 'Body Padding Right (px)', type: 'number', default: 32 },
    { key: 'bodyPaddingBottom', label: 'Body Padding Bottom (px)', type: 'number', default: 32 },
    { key: 'bodyPaddingLeft', label: 'Body Padding Left (px)', type: 'number', default: 32 },
    { key: 'bodyMarginTop', label: 'Body Margin Top (px)', type: 'number', default: 0 },
    { key: 'bodyMarginRight', label: 'Body Margin Right (px)', type: 'number', default: 0 },
    { key: 'bodyMarginBottom', label: 'Body Margin Bottom (px)', type: 'number', default: 0 },
    { key: 'bodyMarginLeft', label: 'Body Margin Left (px)', type: 'number', default: 0 },
    { key: 'footerPaddingTop', label: 'Footer Padding Top (px)', type: 'number', default: 16 },
    { key: 'footerPaddingRight', label: 'Footer Padding Right (px)', type: 'number', default: 16 },
    { key: 'footerPaddingBottom', label: 'Footer Padding Bottom (px)', type: 'number', default: 16 },
    { key: 'footerPaddingLeft', label: 'Footer Padding Left (px)', type: 'number', default: 16 },
    { key: 'footerMarginTop', label: 'Footer Margin Top (px)', type: 'number', default: 0 },
    { key: 'footerMarginRight', label: 'Footer Margin Right (px)', type: 'number', default: 0 },
    { key: 'footerMarginBottom', label: 'Footer Margin Bottom (px)', type: 'number', default: 0 },
    { key: 'footerMarginLeft', label: 'Footer Margin Left (px)', type: 'number', default: 0 },
    { key: 'sidebarPaddingTop', label: 'Sidebar Padding Top (px)', type: 'number', default: 16 },
    { key: 'sidebarPaddingRight', label: 'Sidebar Padding Right (px)', type: 'number', default: 16 },
    { key: 'sidebarPaddingBottom', label: 'Sidebar Padding Bottom (px)', type: 'number', default: 16 },
    { key: 'sidebarPaddingLeft', label: 'Sidebar Padding Left (px)', type: 'number', default: 16 },
    { key: 'sidebarMarginTop', label: 'Sidebar Margin Top (px)', type: 'number', default: 0 },
    { key: 'sidebarMarginRight', label: 'Sidebar Margin Right (px)', type: 'number', default: 0 },
    { key: 'sidebarMarginBottom', label: 'Sidebar Margin Bottom (px)', type: 'number', default: 0 },
    { key: 'sidebarMarginLeft', label: 'Sidebar Margin Left (px)', type: 'number', default: 0 },
    { key: 'headerBorderSize', label: 'Header Border Size', type: 'text', default: '0' },
    { key: 'headerBorderStyle', label: 'Header Border Style', type: 'select', default: 'solid', options: ['none','solid','dashed','dotted','double'] },
    { key: 'headerBorderColor', label: 'Header Border Color', type: 'color', default: '#e5e7eb' },
    { key: 'headerBorderRadiusTopLeft', label: 'Header Radius TL', type: 'text', default: '0' },
    { key: 'headerBorderRadiusTopRight', label: 'Header Radius TR', type: 'text', default: '0' },
    { key: 'headerBorderRadiusBottomRight', label: 'Header Radius BR', type: 'text', default: '0' },
    { key: 'headerBorderRadiusBottomLeft', label: 'Header Radius BL', type: 'text', default: '0' },
    { key: 'bodyBorderSize', label: 'Body Border Size', type: 'text', default: '0' },
    { key: 'bodyBorderStyle', label: 'Body Border Style', type: 'select', default: 'solid', options: ['none','solid','dashed','dotted','double'] },
    { key: 'bodyBorderColor', label: 'Body Border Color', type: 'color', default: '#e5e7eb' },
    { key: 'bodyBorderRadiusTopLeft', label: 'Body Radius TL', type: 'text', default: '0' },
    { key: 'bodyBorderRadiusTopRight', label: 'Body Radius TR', type: 'text', default: '0' },
    { key: 'bodyBorderRadiusBottomRight', label: 'Body Radius BR', type: 'text', default: '0' },
    { key: 'bodyBorderRadiusBottomLeft', label: 'Body Radius BL', type: 'text', default: '0' },
    { key: 'footerBorderSize', label: 'Footer Border Size', type: 'text', default: '0' },
    { key: 'footerBorderStyle', label: 'Footer Border Style', type: 'select', default: 'solid', options: ['none','solid','dashed','dotted','double'] },
    { key: 'footerBorderColor', label: 'Footer Border Color', type: 'color', default: '#e5e7eb' },
    { key: 'footerBorderRadiusTopLeft', label: 'Footer Radius TL', type: 'text', default: '0' },
    { key: 'footerBorderRadiusTopRight', label: 'Footer Radius TR', type: 'text', default: '0' },
    { key: 'footerBorderRadiusBottomRight', label: 'Footer Radius BR', type: 'text', default: '0' },
    { key: 'footerBorderRadiusBottomLeft', label: 'Footer Radius BL', type: 'text', default: '0' },
    { key: 'sidebarBorderSize', label: 'Sidebar Border Size', type: 'text', default: '0' },
    { key: 'sidebarBorderStyle', label: 'Sidebar Border Style', type: 'select', default: 'solid', options: ['none','solid','dashed','dotted','double'] },
    { key: 'sidebarBorderColor', label: 'Sidebar Border Color', type: 'color', default: '#e5e7eb' },
    { key: 'sidebarBorderRadiusTopLeft', label: 'Sidebar Radius TL', type: 'text', default: '0' },
    { key: 'sidebarBorderRadiusTopRight', label: 'Sidebar Radius TR', type: 'text', default: '0' },
    { key: 'sidebarBorderRadiusBottomRight', label: 'Sidebar Radius BR', type: 'text', default: '0' },
    { key: 'sidebarBorderRadiusBottomLeft', label: 'Sidebar Radius BL', type: 'text', default: '0' },
    { key: 'homePageSlug', label: 'Home Page Slug', type: 'text', default: 'posts', helper: 'Slug of the page to render on /' }
  ],
  defaultSettings: {
    primaryColor: '#e06e26',
    accentColor: '#319ea4',
    textColor: '#1f2933',
    backgroundColor: '#f9fafb',
    maxWidth: 1200,
    containerPaddingTop: 0,
    containerPaddingRight: 0,
    containerPaddingBottom: 0,
    containerPaddingLeft: 0,
    containerMarginTop: 0,
    containerMarginRight: 0,
    containerMarginBottom: 0,
    containerMarginLeft: 0,
    headerPaddingTop: 16,
    headerPaddingRight: 16,
    headerPaddingBottom: 16,
    headerPaddingLeft: 16,
    headerMarginTop: 0,
    headerMarginRight: 0,
    headerMarginBottom: 0,
    headerMarginLeft: 0,
    bodyPaddingTop: 32,
    bodyPaddingRight: 32,
    bodyPaddingBottom: 32,
    bodyPaddingLeft: 32,
    bodyMarginTop: 0,
    bodyMarginRight: 0,
    bodyMarginBottom: 0,
    bodyMarginLeft: 0,
    footerPaddingTop: 16,
    footerPaddingRight: 16,
    footerPaddingBottom: 16,
    footerPaddingLeft: 16,
    footerMarginTop: 0,
    footerMarginRight: 0,
    footerMarginBottom: 0,
    footerMarginLeft: 0,
    sidebarPaddingTop: 16,
    sidebarPaddingRight: 16,
    sidebarPaddingBottom: 16,
    sidebarPaddingLeft: 16,
    sidebarMarginTop: 0,
    sidebarMarginRight: 0,
    sidebarMarginBottom: 0,
    sidebarMarginLeft: 0,
    headerBorderSize: '0',
    headerBorderStyle: 'solid',
    headerBorderColor: '#e5e7eb',
    headerBorderRadiusTopLeft: '0',
    headerBorderRadiusTopRight: '0',
    headerBorderRadiusBottomRight: '0',
    headerBorderRadiusBottomLeft: '0',
    bodyBorderSize: '0',
    bodyBorderStyle: 'solid',
    bodyBorderColor: '#e5e7eb',
    bodyBorderRadiusTopLeft: '0',
    bodyBorderRadiusTopRight: '0',
    bodyBorderRadiusBottomRight: '0',
    bodyBorderRadiusBottomLeft: '0',
    footerBorderSize: '0',
    footerBorderStyle: 'solid',
    footerBorderColor: '#e5e7eb',
    footerBorderRadiusTopLeft: '0',
    footerBorderRadiusTopRight: '0',
    footerBorderRadiusBottomRight: '0',
    footerBorderRadiusBottomLeft: '0',
    sidebarBorderSize: '0',
    sidebarBorderStyle: 'solid',
    sidebarBorderColor: '#e5e7eb',
    sidebarBorderRadiusTopLeft: '0',
    sidebarBorderRadiusTopRight: '0',
    sidebarBorderRadiusBottomRight: '0',
    sidebarBorderRadiusBottomLeft: '0',
    homePageSlug: 'posts'
  }
}
